name: Multiwerf Release Pub lisher (new)

on:
  create:
  release:
  watch:
  push:

env:
  GO111MODULE: on

jobs:
  publish_release:
    name: Publish werf release
    runs-on: [self-hosted, linux, builder]
    steps:
    - name: Publish release
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      shell: bash
