name: Release Publisher
on:
  push:
    tags:
    - 'v*'

env:
  GO111MODULE: on

jobs:
  publish_release:
    name: Publish werf release
    runs-on: [self-hosted, linux, builder]
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Publish release
      run: |
        ./scripts/publish_release.sh ${GITHUB_REF#refs/tags/}
      shell: bash
      env:
        S3_REGION: ${{ secrets.S3_REGION }}
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        PUBLISH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
