name: Converge website
on:
  push:
    branches: [master]

env:
  WERF_REPO: "ghcr.io/${{ github.repository_owner }}/trdl"

jobs:

  converge:
    name: Converge site to Production
    runs-on: tfprod-trdl
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Converge
      uses: werf/actions/converge@v1.2
      with:
        env: production
      env:
        WERF_DIR: "docs"
        WERF_KUBE_CONTEXT: prod
