name: Test website
on:
  pull_request:
    types: [labeled, synchronize]

env:
  WERF_REPO: "ghcr.io/${{ github.repository_owner }}/trdl"

jobs:

  converge:
    name: Converge to Test
    runs-on: tfprod-trdl
    if: github.event.label.name == 'test docs' || contains( github.event.pull_request.labels.*.name, 'test docs' )
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Converge
      uses: werf/actions/converge@v1.2
      with:
        env: test
      env:
        WERF_DIR: "docs"
        WERF_KUBE_CONTEXT: dev
